server:
  port: 8081

spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost:3366/mydb?useUnicode=true&characterEncoding=utf-8
        username: root
        password: qin123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        maxOpenPreparedStatements: 20

mybatis:
  mapper-locations: classpath:mapXml/*.xml
  type-aliases-package: com.example.myblogserver.model

mapper:
  mappers:  com.example.myblogserver.mapper
  not-empty: false
  identity: MYSQL

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check